#!/usr/bin/env php
<?php
date_default_timezone_set('Europe/Kyiv');

require __DIR__ . '/vendor/autoload.php';

$dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
$dotenv->load();

$shortOptions = "p::s::r::";
$longOptions = ["project::", "service::", "restore::"];

$options = getopt($shortOptions, $longOptions);

$projectEnv = $options['project'] ?? ($options['p'] ?? ($argv[1] ?? ''));
$services = $options['service'] ?? ($options['s'] ?? ($argv[2] ?? null));
$restore = $options['restore'] ?? ($options['r'] ?? ($argv[3] ?? false));

$config = require(__DIR__ . '/config/params.php');

$service = new App\EnvReplacer($config);
$service->run($projectEnv, $services, $restore);

